language: node_js
node_js:
  - '12'
before_install:
  - sudo ulimit -n unlimited
  - npm i npminstall -g
install:
  - npminstall
script:
  - npm run ci
after_script:
  - npminstall codecov && codecov
